# Generated by Django 5.0.1 on 2024-03-07 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BLogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, default='fallback.png', upload_to=''),
        ),
    ]
