# Generated by Django 5.0.1 on 2024-03-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_clientmassage'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmassage',
            name='massage',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
