# Generated by Django 5.0.1 on 2024-03-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_clientmassage_massage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmassage',
            name='massage',
            field=models.CharField(default='', editable=False, max_length=1000),
        ),
        migrations.AlterField(
            model_name='clientmassage',
            name='sender_email',
            field=models.CharField(editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='clientmassage',
            name='sender_name',
            field=models.CharField(editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='clientmassage',
            name='subject',
            field=models.CharField(editable=False, max_length=70),
        ),
    ]
