# Generated by Django 5.0.1 on 2024-03-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_clientmassage_massage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmassage',
            name='massage',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='clientmassage',
            name='sender_email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='clientmassage',
            name='sender_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='clientmassage',
            name='subject',
            field=models.CharField(max_length=70),
        ),
    ]
